name: progress_indicator_button
description: A simple button which can transform and show a progress indicator.
version: 0.0.3
author: Pascal Brosinski<pascal@brosinski.eu>
homepage: https://github.com/PascalAC/progress_button

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
