name: spinner_button
version: 0.5.0
homepage: https://github.com/SunnyApp/progress_button
description: A simple button which can transform and show a progress indicator.  Forked from another project
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
dev_dependencies: 
  dartxx: any
  flutter_test: 
    sdk: flutter
authors: 
  - Pascal Brosinski<pascal@brosinski.eu>
  - Eric Martineau<edspuzzle@gmail.com>
